### ISSUE TITLE
Remove analyses from "Data Set" chapters in appendix 

### ISSUE THREAD

**Issue by michael-franke** [michael-franke/intro-data-analysis#58]
Since the web-book features different kinds of analyses, it's best to NOT have yet different (sometimes hierarchical) analyses also in the appendix.

**Comment by ooezenoglu** [comment]
Should the analysis sections be commented out or removed entirely?

**Comment by michael-franke** [comment]
commented out.

**Comment by MarauderPixie** [comment]
All done. A short note about html-comments (`strg/cmd + shift + c`): apparently, R code (inline as well as chunks) that is commented out via `<!--`/`-->` nonetheless gets executed _somehow™_ during compilation. I don't fully understand what's going on, but the current workaround is to set (already commented out) code chunks to `eval = FALSE` and remove the `r ` from the beginning of inline code...
